version: '3.9'

services:
  kc-db:
    image: postgres:14.4-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    tmpfs: /var/lib/postgresql/data
    restart: unless-stopped
  db:
    image: postgres:14.4-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_DB: hulk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data
    tmpfs: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    restart: unless-stopped
  db-migrator:
    image: drop149/asasdb:latest
    command: migrate -i -d hulk
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/hulk
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: password123
    depends_on:
      - db
    links:
      - db
    restart: always
  keycloak:
    build:
      context: ./deployment/dev/keycloak
      dockerfile: Dockerfile
      args:
        - KC_DATA=default.json
    command: start-dev
    healthcheck:
      test: ['CMD', 'curl', '-skXGET', 'http://localhost:8080/health']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: kc-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES_DISABLED: preview,web-authn,docker,openshift-integration
    ports:
      - 8080:8080
    links:
      - kc-db
    depends_on:
      - kc-db
  cache:
    image: redis:7.0.2-alpine
    ports:
      - '6379:6379'
    expose:
      - 6379
    restart: unless-stopped
